name: Veracode Static Analysis Demo
on: 
  push:
    branches:
      - '*'
      - '!main'
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Zip Project
        run: zip -R project.zip '*.py' '*.js' '*.php' '*.ts' 'requirements.txt'
        env:
          build-name: project.zip

# Copy files from repository to docker container so the next uploadandscan action can access them.
      - name: Copy artifact to container
        uses: actions/upload-artifact@v2
        with:
          path: project.zip

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'Verademo API'
          createprofile: false
          filepath: './project.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          sandboxname: 'Github - ${{ github.ref }}'
          createsandbox: 'true'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
